SELECT * FROM ARTISTAS;

SELECT * FROM ARTISTAS WHERE NOMBRE_ARTISTA LIKE 'P%';

SELECT * FROM ARTISTAS ORDER BY DIRECCION_ARTISTA;

SELECT A.NOMBRE_ARTISTA, A.TELEFONO_ARTISTA, AE.NOMBRE_ENTREVISTADOR, AE.FECHA_ENTREVISTA
FROM `ARTISTAS` A
JOIN ARTISTA_ENTREVISTA AE ON A.NOMBRE_ARTISTA = AE.NOMBRE_ARTISTA;

SELECT A.NOMBRE_ARTISTA, A.TELEFONO_ARTISTA, AE.NOMBRE_ENTREVISTADOR, AE.FECHA_ENTREVISTA 
FROM `ARTISTAS` A 
LEFT JOIN ARTISTA_ENTREVISTA AE ON A.NOMBRE_ARTISTA = AE.NOMBRE_ARTISTA;

SELECT A.NOMBRE_ARTISTA, A.TELEFONO_ARTISTA, AE.NOMBRE_ENTREVISTADOR, AE.FECHA_ENTREVISTA 
FROM `ARTISTAS` A 
RIGHT JOIN ARTISTA_ENTREVISTA AE ON A.NOMBRE_ARTISTA = AE.NOMBRE_ARTISTA;

SELECT A.NOMBRE_ARTISTA, A.TELEFONO_ARTISTA, AE.NOMBRE_ENTREVISTADOR, AE.FECHA_ENTREVISTA 
FROM `ARTISTAS` A 
INNER JOIN ARTISTA_ENTREVISTA AE ON A.NOMBRE_ARTISTA = AE.NOMBRE_ARTISTA;

SELECT 
	A.NOMBRE_ARTISTA, 
    (SELECT (ATV.TOTAL_VENTAS_ANUAL + ATV.TOTAL_VENTAS_ANIO_ANTERIOR) 
     FROM ARTISTA_TOTALES_VENTAS ATV 
     WHERE A.NOMBRE_ARTISTA = ATV.NOMBRE_ARTISTA) AS `TOTAL_VENTAS` 
FROM `ARTISTAS` A

SELECT 
	A.*
FROM
(
    SELECT 
		A.NOMBRE_ARTISTA, 
    	(SELECT (ATV.TOTAL_VENTAS_ANUAL + ATV.TOTAL_VENTAS_ANIO_ANTERIOR) 
    	 FROM ARTISTA_TOTALES_VENTAS ATV 
    	 WHERE A.NOMBRE_ARTISTA = ATV.NOMBRE_ARTISTA) AS `TOTAL_VENTAS` 
	FROM `ARTISTAS` A
) AS A
WHERE A.TOTAL_VENTAS > 1000;

SELECT 
	V.NUMERO_VENTA, V.FECHA_VENTA, V.VENTA_FINAL, C.NOMBRE_COLECCIONISTA
FROM VENTA V
JOIN COLECCIONISTAS C ON C.NOMBRE_COLECCIONISTA = V.NOMBRE_COLECCIONISTA;

SELECT 
	V.NUMERO_VENTA, V.FECHA_VENTA, V.VENTA_FINAL, C.NOMBRE_COLECCIONISTA
FROM VENTA V
LEFT JOIN COLECCIONISTAS C ON C.NOMBRE_COLECCIONISTA = V.NOMBRE_COLECCIONISTA;

SELECT 
	V.NUMERO_VENTA, V.FECHA_VENTA, V.VENTA_FINAL, C.NOMBRE_COLECCIONISTA
FROM VENTA V
RIGHT JOIN COLECCIONISTAS C ON C.NOMBRE_COLECCIONISTA = V.NOMBRE_COLECCIONISTA;

SELECT 
	V.NUMERO_VENTA, V.FECHA_VENTA, V.VENTA_FINAL, C.NOMBRE_COLECCIONISTA
FROM VENTA V
INNER JOIN COLECCIONISTAS C ON C.NOMBRE_COLECCIONISTA = V.NOMBRE_COLECCIONISTA;


SELECT 
	V.NUMERO_VENTA, V.FECHA_VENTA, V.VENTA_FINAL, CC.NOMBRE_CLIENTE, CT.TOTAL_COMPRAS_A_LA_FECHA
FROM VENTA V
JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
JOIN CLIENTES_TOTALES CT ON CT.RUN_CLIENTE = CC.RUN_CLIENTE;

SELECT
	A.RUN_CLIENTE,
    A.NOMBRE_CLIENTE,
	A.TOTAL_COMPRAS_A_LA_FECHA_SUM
FROM
(
	SELECT 
		CC.RUN_CLIENTE, 
    	CC.NOMBRE_CLIENTE, 
    	(
			SELECT SUM(CT.TOTAL_COMPRAS_A_LA_FECHA) AS TOTAL_COMPRAS_A_LA_FECHA_SUM 
			FROM CLIENTES_TOTALES CT 
        	WHERE CT.RUN_CLIENTE = CC.RUN_CLIENTE 
        	GROUP BY CT.RUN_CLIENTE
    	) AS TOTAL_COMPRAS_A_LA_FECHA_SUM
	FROM CLIENTE_COMPRADOR CC
) AS A
WHERE A.TOTAL_COMPRAS_A_LA_FECHA_SUM >= 10
ORDER BY A.NOMBRE_CLIENTE;


