--Cuando queremos consultar columnas o atributos de dos o mas tablas se debe utilizar JOIN
SELECT * FROM ESTUDIANTE E
LEFT JOIN MATRICULADO M ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
LEFT JOIN CURSO C ON C.ID_CURSO = M.ID_CURSO
ORDER BY E.ID_ESTUDIANTE ASC;

SELECT * FROM ESTUDIANTE E
RIGHT JOIN MATRICULADO M ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
RIGHT JOIN CURSO C ON C.ID_CURSO = M.ID_CURSO
ORDER BY E.ID_ESTUDIANTE ASC;

SELECT * FROM ESTUDIANTE E
INNER JOIN MATRICULADO M ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
INNER JOIN CURSO C ON C.ID_CURSO = M.ID_CURSO
ORDER BY E.ID_ESTUDIANTE ASC;

SELECT * FROM ESTUDIANTE E
FULL JOIN MATRICULADO M ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
FULL JOIN CURSO C ON C.ID_CURSO = M.ID_CURSO
ORDER BY E.ID_ESTUDIANTE ASC;