-- Insertamos datos a las tablas ESTUDIANTE, CURSO y MATRICULADO (en ese orden)
BEGIN TRANSACTION
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE,NOMBRES,APELLIDOS,RUN) VALUES(1,'SACARIAS','FLORES DEL CAMPO','00.000.000-0');
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE,NOMBRES,APELLIDOS,RUN) VALUES(2,'ARMANDO','CASAS DEL BOSQUE','11.111.111-1');
INSERT INTO ESTUDIANTE (ID_ESTUDIANTE,NOMBRES,APELLIDOS,RUN) VALUES(3,'ALAN','BRITO DELGADO','22.222.222-2');

INSERT INTO CURSO(ID_CURSO,NOMBRE_CURSO,CODIGO_CURSO,ID_DOCENTE) VALUES(1,'Bases de Datos 2','BD22020',1);
INSERT INTO CURSO(ID_CURSO,NOMBRE_CURSO,CODIGO_CURSO,ID_DOCENTE) VALUES(2,'Taller de Sistemas 1','TS12020',2);

-- La tabla MATRICULADO como referencian a las tablas ESTUDIANTE y CURSO, deben insertar datos al ultimo, ya que como existe una dependencia al ingresar un valor que no existe en las tablas que se referencian habrian un error por parte del SGBD.
INSERT INTO MATRICULADO(ID_MATRICULADO,ID_ESTUDIANTE,ID_CURSO) VALUES(1,1,1);
INSERT INTO MATRICULADO(ID_MATRICULADO,ID_ESTUDIANTE,ID_CURSO) VALUES(2,2,1);
INSERT INTO MATRICULADO(ID_MATRICULADO,ID_ESTUDIANTE,ID_CURSO) VALUES(3,3,2);
INSERT INTO MATRICULADO(ID_MATRICULADO,ID_ESTUDIANTE,ID_CURSO) VALUES(4,1,2);
COMMIT;
