CREATE OR REPLACE FUNCTION SUMATORIA_ARTISTA_TOTALES_VENTAS (P_NOMBRE_ARTISTA IN VARCHAR)
    RETURN NUMBER
AS
    -- VARIABLES
    VAR_SUMATORIA NUMBER := 0;
    ERROR_NULO EXCEPTION;
BEGIN
    SELECT 
        (TOTAL_VENTAS_ANUAL + TOTAL_VENTAS_ANIO_ANTERIOR) INTO VAR_SUMATORIA
    FROM ARTISTA_TOTALES_VENTAS ATV
    WHERE ATV.NOMBRE_ARTISTA = P_NOMBRE_ARTISTA;
    
    IF VAR_SUMATORIA IS NULL THEN
        RAISE ERROR_NULO;
    ELSE
        RETURN VAR_SUMATORIA;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error, resultado suma es nulo');
END SUMATORIA_ARTISTA_TOTALES_VENTAS;