CREATE OR REPLACE FUNCTION VALIDAR_CALCULO_VENTA (P_NUMERO_VENTA IN NUMBER)
    RETURN VARCHAR
AS 
    CURSOR C_VENTA IS SELECT NUMERO_VENTA, PRECIO_VENTA_FINAL, COMISION, VENTA_FINAL FROM VENTA;
    VAR_VALIDAR_VENTA VARCHAR(200) := 'TRUE';
BEGIN
    FOR R_VENTA IN C_VENTA LOOP
        IF (R_VENTA.PRECIO_VENTA_FINAL + R_VENTA.COMISION) = R_VENTA.VENTA_FINAL AND R_VENTA.NUMERO_VENTA = P_NUMERO_VENTA THEN
            VAR_VALIDAR_VENTA := 'TRUE';
        ELSE
            VAR_VALIDAR_VENTA := 'FALSE';
        END IF;
    END LOOP;
    
    RETURN VAR_VALIDAR_VENTA;
END VALIDAR_CALCULO_VENTA;