CREATE OR REPLACE FUNCTION SUMATORIA_CLIENTES_TOTALES (P_RUN_CLIENTE IN VARCHAR)
    RETURN NUMBER
AS
    VAR_SUMA_TOTAL_COMPRAS NUMBER := 0;
    ERROR_NULO EXCEPTION;
BEGIN
    SELECT 
        (TOTAL_COMPRAS_ANIO_PASADO + TOTAL_COMPRAS_A_LA_FECHA) INTO VAR_SUMA_TOTAL_COMPRAS
    FROM CLIENTES_TOTALES CT
    WHERE CT.RUN_CLIENTE = P_RUN_CLIENTE;
    
    IF VAR_SUMA_TOTAL_COMPRAS IS NULL THEN
        RAISE ERROR_NULO;
    ELSE
        RETURN VAR_SUMA_TOTAL_COMPRAS;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error, suma nula');
END SUMATORIA_CLIENTES_TOTALES;