CREATE OR REPLACE PROCEDURE CAMBIO_DIRECCION_VENDEDOR (P_RUN_VENDEDOR IN VARCHAR, P_NUEVA_DIRECCION IN VARCHAR)
AS
    -- VARIABLES
    ERROR_NULO EXCEPTION;
BEGIN
    IF P_RUN_VENDEDOR IS NOT NULL AND P_NUEVA_DIRECCION IS NOT NULL THEN
        UPDATE VENDEDOR
        SET DIRECCION_VENDEDOR = P_NUEVA_DIRECCION
        WHERE RUN_VENDEDOR = P_RUN_VENDEDOR;
    ELSE
        RAISE ERROR_NULO;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error, datos nulos, modificar');
END CAMBIO_DIRECCION_VENDEDOR;