CREATE OR REPLACE PROCEDURE CAMBIAR_TEMA_EXPOSICION (P_TITULO_EXPOSICION IN NUMBER, P_TEMA_EXPOSICION_NEW IN VARCHAR)
AS
    -- VARIABLES
    ERROR_NULO EXCEPTION;
BEGIN
    IF P_TITULO_EXPOSICION IS NOT NULL AND P_TEMA_EXPOSICION_NEW IS NOT NULL THEN
        UPDATE EXPOSICIONES
        SET TEMA_EXPOSICION = P_TEMA_EXPOSICION_NEW
        WHERE TITULO_EXPOSICION = P_TITULO_EXPOSICION;
    ELSE
        RAISE ERROR_NULO;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error parametros nulos');
END CAMBIAR_TEMA_EXPOSICION;