SELECT NOMBRE_ARTISTA, SUMATORIA_ARTISTA_TOTALES_VENTAS(NOMBRE_ARTISTA) SUMA_VENTAS
FROM ARTISTA_TOTALES_VENTAS;

SELECT 
    CT.RUN_CLIENTE, 
    CC.NOMBRE_CLIENTE, 
    SUMATORIA_CLIENTES_TOTALES(CT.RUN_CLIENTE) SUMA_TOTAL
FROM CLIENTES_TOTALES CT
JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = CT.RUN_CLIENTE;

SELECT 
    NUMERO_VENTA, 
    VALIDAR_CALCULO_VENTA(NUMERO_VENTA) SUMA_VALIDA
FROM VENTA;