DECLARE
  CURSOR C_ESTUDIANTE IS SELECT ID_ESTUDIANTE, NOMBRES, APELLIDOS, RUN FROM ESTUDIANTE;
  C_ID_ESTUDIANTE NUMERIC(38);
  C_NOMBRES VARCHAR (4000);
  C_APELLIDOS VARCHAR (4000); 
  C_RUN VARCHAR (4000);
BEGIN
  OPEN C_ESTUDIANTE;
  
  FETCH C_ESTUDIANTE INTO C_ID_ESTUDIANTE, C_NOMBRES, C_APELLIDOS, C_RUN;
  
  IF C_ESTUDIANTE%FOUND THEN
    DBMS_OUTPUT.PUT_LINE(C_ID_ESTUDIANTE || ' ' || C_NOMBRES || ' ' || C_APELLIDOS || ' ' || C_RUN);
  END IF;
  
  CLOSE C_ESTUDIANTE;
END;
/