CREATE VIEW VISTA_CANT_CURSO_EST AS
(
    SELECT 
        NOMBRES, 
        APELLIDOS, 
        (SELECT COUNT(ID_CURSO) 
        FROM MATRICULADO M 
        WHERE M.ID_ESTUDIANTE = E.ID_ESTUDIANTE) CANT_CURSO
    FROM ESTUDIANTE E
);