CREATE OR REPLACE FUNCTION 
CONCATENAR_NOMBRE_APELLIDO (IDENTIFICADOR IN NUMBER)
	RETURN VARCHAR
AS
	VAR_NOMBRE_APELLIDO VARCHAR2(242);
	ERROR_NULO EXCEPTION;
BEGIN
	SELECT CONCAT(CONCAT(NOMBRES, ' '), APELLIDOS) INTO VAR_NOMBRE_APELLIDO
	FROM ESTUDIANTE
	WHERE ID_ESTUDIANTE = IDENTIFICADOR;

	IF VAR_NOMBRE_APELLIDO IS NULL THEN
		RAISE ERROR_NULO;
	ELSE
		RETURN VAR_NOMBRE_APELLIDO;
	END IF;
EXCEPTION
	WHEN ERROR_NULO THEN
		DBMS_OUTPUT.PUT_LINE('Error, string nulos');
END CONCATENAR_NOMBRE_APELLIDO;