CREATE OR REPLACE VIEW VISTA_CANT_CURSO_EST AS
SELECT
    NOMBRES,
    APELLIDOS, 
    CANT_CURSO
FROM
(
    SELECT 
        E.NOMBRES, 
        E.APELLIDOS, 
        (SELECT COUNT(M.ID_CURSO) 
        FROM MATRICULADO M 
        WHERE M.ID_ESTUDIANTE = E.ID_ESTUDIANTE) CANT_CURSO
    FROM ESTUDIANTE E
) 
ORDER BY NOMBRES ASC;