DECLARE
  NUMERO NUMBER(2) NOT NULL DEFAULT 20;
  PALABRA VARCHAR(200) := 'Hola Mundo';
BEGIN
  DBMS_OUTPUT.PUT_LINE('Numero: ' || TO_CHAR(NUMERO));
  DBMS_OUTPUT.PUT_LINE('SALUDO: ' || PALABRA);
END;
/