DROP TABLE PRODUCTO_FECHAS_PROCESO CASCADE CONSTRAINTS ;

CREATE TABLE PRODUCTO_FECHAS_PROCESO
(
  ID_PRODUCTO_FECHAS_PROCESO  INTEGER NOT NULL ,
  FECHA_COMPRA                TIMESTAMP
);
ALTER TABLE PRODUCTO_FECHAS_PROCESO ADD CONSTRAINT PRODUCTO_FECHAS_PROCESO_PK 
PRIMARY KEY ( ID_PRODUCTO_FECHAS_PROCESO );

COMMIT;