CREATE VIEW CANT_CURSO_ESTUDIANTE AS
(
  SELECT
    NOMBRES,
    APELLIDOS,
    CANTIDAD_CURSO
  FROM 
  (
    SELECT 
      E.NOMBRES, 
      E.APELLIDOS,
      (
        SELECT COUNT(1) CANTIDAD_ESTUDIANTE
        FROM MATRICULADO M 
        WHERE M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
        GROUP BY M.ID_ESTUDIANTE) CANTIDAD_CURSO
    FROM ESTUDIANTE E
  )
);