DECLARE
  MULTIPLO_A NUMBER := 3;
  MULTIPLO_B NUMBER := 0;
  RESULTADO NUMBER := 0;
  ERROR_MULTIPLICACION_CERO EXCEPTION;
BEGIN
  IF MULTIPLO_A*MULTIPLO_B = 0 THEN
    RAISE ERROR_MULTIPLICACION_CERO;
  ELSE
    RESULTADO := MULTIPLO_A*MULTIPLO_B;
    DBMS_OUTPUT.PUT_LINE('Resultado: ' || TO_CHAR(RESULTADO));
  END IF;
EXCEPTION
  WHEN ERROR_MULTIPLICACION_CERO THEN
    DBMS_OUTPUT.PUT_LINE('Trata de multiplicar por cero, modifique valores distinto cero.');
END;
/