DECLARE
  CURSOR C_ESTUDIANTE IS SELECT ID_ESTUDIANTE, NOMBRES, APELLIDOS, RUN FROM ESTUDIANTE;
  C_ID_ESTUDIANTE NUMERIC(38);
  C_NOMBRES VARCHAR (4000);
  C_APELLIDOS VARCHAR (4000); 
  C_RUN VARCHAR (4000);
BEGIN
  OPEN C_ESTUDIANTE;
  
  LOOP 
    FETCH C_ESTUDIANTE INTO C_ID_ESTUDIANTE, C_NOMBRES, C_APELLIDOS, C_RUN;
    DBMS_OUTPUT.PUT_LINE(C_ID_ESTUDIANTE || ' ' || C_NOMBRES || ' ' || C_APELLIDOS || ' ' || C_RUN);
    EXIT WHEN C_ESTUDIANTE%NOTFOUND;
  END LOOP;
  
  CLOSE C_ESTUDIANTE;
END;
/