DECLARE
    INDICE NUMBER := 1;
    TOTAL NUMBER := 0;
BEGIN
    LOOP
        TOTAL := TOTAL + INDICE;
        DBMS_OUTPUT.PUT_LINE('INDICE: ' || TO_CHAR(INDICE));
    	INDICE := INDICE + 1;
    	EXIT WHEN INDICE >= 6;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('TOTAL: ' || TO_CHAR(TOTAL));
END;
/