DECLARE
  NUMERADOR NUMBER := 1;
  DENOMINADOR NUMBER := 0;
  RESULTADO NUMBER := 0;
BEGIN
  RESULTADO := NUMERADOR / DENOMINADOR;
EXCEPTION
  WHEN ZERO_DIVIDE THEN
    DBMS_OUTPUT.PUT_LINE('División por cero, modificar denominador.');
END;
/