DECLARE
    INDICE NUMBER := 1;
    TOTAL NUMBER := 0;
BEGIN
    WHILE INDICE <= 5 LOOP
        TOTAL := TOTAL + INDICE;
        DBMS_OUTPUT.PUT_LINE('INDICE: ' || TO_CHAR(INDICE));
        INDICE := INDICE + 1;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('TOTAL: ' || TO_CHAR(TOTAL));
END;
/