CREATE OR REPLACE PROCEDURE ACTUALIZAR_NOMBRE (NOMBRE_ANTIGUO VARCHAR, NOMBRE_NUEVO VARCHAR)
IS
	-- 
	ERROR_NULO EXCEPTION;
BEGIN
	IF NOMBRE_ANTIGUO IS NOT NULL AND NOMBRE_NUEVO IS NOT NULL THEN
		UPDATE ESTUDIANTE
		SET NOMBRES = NOMBRE_NUEVO
		WHERE NOMBRES = NOMBRE_ANTIGUO;
	ELSE
		RAISE ERROR_NULO;
	END IF;
EXCEPTION
	WHEN ERROR_NULO THEN
		DBMS_OUTPUT.PUT_LINE('Error, nombres nulos, agregar nombres.');
END;
