CREATE OR REPLACE FUNCTION CANT_OBRAS_ARTE_POR_ARTISTA (P_NOMBRE_ARTISTA IN VARCHAR)
    RETURN NUMBER
AS 
    VAR_CANT_TITULO_OBRA NUMBER := 0;
    ERROR_NULO EXCEPTION;
BEGIN
    SELECT 
        COUNT(TITULO_OBRA) INTO VAR_CANT_TITULO_OBRA 
    FROM OBRAS_ARTE 
    WHERE NOMBRE_ARTISTA = P_NOMBRE_ARTISTA
    GROUP BY NOMBRE_ARTISTA;
    
    IF VAR_CANT_TITULO_OBRA IS NULL THEN
        RAISE ERROR_NULO;
    ELSE
        RETURN VAR_CANT_TITULO_OBRA;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error, resultado nulo');
END CANT_OBRAS_ARTE_POR_ARTISTA;

------
SELECT 
    NOMBRE_ARTISTA, 
    CANT_OBRAS_ARTE_POR_ARTISTA(NOMBRE_ARTISTA) CANTIDAD
FROM OBRAS_ARTE
GROUP BY NOMBRE_ARTISTA;