CREATE OR REPLACE PROCEDURE INCREMENTO_PRECIO_SOLICITADO (P_PORCENTAJE_PRECIO_SOLICITADO IN INTEGER)
IS
    CURSOR C_PRECIO_SOLICITADO IS SELECT NOMBRE_ARTISTA, TITULO_OBRA, PRECIO_SOLICITADO FROM OBRAS_ARTE;
    V_NOMBRE_ARTISTA VARCHAR(255);
    V_TITULO_OBRA VARCHAR(255);
    V_PRECIO_SOLICITADO INTEGER := 0;
    ERROR_NULO EXCEPTION;
BEGIN
    
    FOR R_PRECIO_SOLICITADO IN C_PRECIO_SOLICITADO LOOP
        
        V_PRECIO_SOLICITADO := ROUND(R_PRECIO_SOLICITADO.PRECIO_SOLICITADO + (R_PRECIO_SOLICITADO.PRECIO_SOLICITADO * (P_PORCENTAJE_PRECIO_SOLICITADO/100)),0);
        V_NOMBRE_ARTISTA := R_PRECIO_SOLICITADO.NOMBRE_ARTISTA;
        V_TITULO_OBRA := R_PRECIO_SOLICITADO.TITULO_OBRA;
        
        IF V_PRECIO_SOLICITADO IS NOT NULL THEN
            UPDATE OBRAS_ARTE
            SET PRECIO_SOLICITADO = V_PRECIO_SOLICITADO
            WHERE NOMBRE_ARTISTA = V_NOMBRE_ARTISTA AND TITULO_OBRA = V_TITULO_OBRA;
        ELSE
            RAISE ERROR_NULO;
        END IF;
    END LOOP;
    
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error Precio Solicitado es nulo');
END INCREMENTO_PRECIO_SOLICITADO;