CREATE OR REPLACE PROCEDURE AGREGAR_MES_FECHA_CONTACTO (P_MES IN INTEGER)
IS
    CURSOR C_FECHA_CONTACTO IS SELECT ID_CONTACTA, FECHA_CONTACTO FROM CONTACTA;
    V_FECHA_CONTACTO DATE;
    V_ID_CONTACTA INTEGER;
    ERROR_NULO EXCEPTION;
BEGIN
    FOR R_FECHA_CONTACTO IN C_FECHA_CONTACTO LOOP
        V_FECHA_CONTACTO := ADD_MONTHS(R_FECHA_CONTACTO.FECHA_CONTACTO,P_MES);
        V_ID_CONTACTA := R_FECHA_CONTACTO.ID_CONTACTA;
        
        IF V_FECHA_CONTACTO IS NOT NULL THEN
            UPDATE CONTACTA
            SET FECHA_CONTACTO = V_FECHA_CONTACTO
            WHERE ID_CONTACTA = V_ID_CONTACTA;
        ELSE
            RAISE ERROR_NULO;
        END IF;
    END LOOP;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error fecha nulca');
END AGREGAR_MES_FECHA_CONTACTO;