UPDATE VENTA
SET FECHA_VENTA = TO_DATE('21-06-2020','DD-MM-YYYY')
WHERE NUMERO_VENTA = 3;


CREATE OR REPLACE FUNCTION CANT_MESES_ENTRE_PRIMERA_ULTIMA_FECHA_VENTA(P_ANIO IN VARCHAR)
    RETURN FLOAT
AS
    VAR_CANT_MESES FLOAT := 0.0;
    ERROR_NULO EXCEPTION;
BEGIN
    SELECT 
        MONTHS_BETWEEN(MAX(FECHA_VENTA),MIN(FECHA_VENTA)) INTO VAR_CANT_MESES
    FROM VENTA
    WHERE TO_CHAR(FECHA_VENTA,'YYYY') = P_ANIO;
    
    IF VAR_CANT_MESES IS NULL THEN
        RAISE ERROR_NULO;
    ELSE
        RETURN VAR_CANT_MESES;
    END IF;

EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error nulo');
END CANT_MESES_ENTRE_PRIMERA_ULTIMA_FECHA_VENTA;

------
SELECT 
    ROUND(CANT_MESES_ENTRE_PRIMERA_ULTIMA_FECHA_VENTA('2020'),0) CANT_MESES 
FROM DUAL




