CREATE OR REPLACE FUNCTION CANT_POTENCIALES_CLIENTES_EXP (P_NOMBRE_POTENCIALES_CLIENTES IN VARCHAR)
    RETURN NUMBER
AS 
    VAR_CANT_TIT_EXP NUMBER := 0;
    ERROR_NULO EXCEPTION;
BEGIN
    SELECT 
        COUNT(E.TITULO_EXPOSICION) INTO VAR_CANT_TIT_EXP
    FROM CONTACTA C
    JOIN POTENCIALES_CLIENTES PC ON PC.NOMBRE_POTENCIALES_CLIENTES = C.NOMBRE_POTENCIALES_CLIENTES
    JOIN EXPOSICIONES E ON E.TITULO_EXPOSICION = C.TITULO_EXPOSICION
    WHERE PC.NOMBRE_POTENCIALES_CLIENTES = P_NOMBRE_POTENCIALES_CLIENTES
    GROUP BY PC.NOMBRE_POTENCIALES_CLIENTES;
    
    IF VAR_CANT_TIT_EXP IS NULL THEN
        RAISE ERROR_NULO;
    ELSE
        RETURN VAR_CANT_TIT_EXP;
    END IF;
EXCEPTION
    WHEN ERROR_NULO THEN
        DBMS_OUTPUT.PUT_LINE('Error, resultado nulo');
END CANT_POTENCIALES_CLIENTES_EXP;

----
SELECT 
    NOMBRE_POTENCIALES_CLIENTES, 
    CANT_POTENCIALES_CLIENTES_EXP(NOMBRE_POTENCIALES_CLIENTES) CANTIDAD_EXP
FROM POTENCIALES_CLIENTES
GROUP BY NOMBRE_POTENCIALES_CLIENTES;