CREATE OR REPLACE PROCEDURE MODIFICACION_PORCENTAJE_COMISION_Y_COMISION (P_PORCENTAJE_COMISION IN NUMBER)
IS
    CURSOR C_NUMERO_VENTA IS SELECT NUMERO_VENTA, PRECIO_VENTA_FINAL FROM VENTA;
    VAR_COMISION NUMBER;
    VAR_VENTA_FINAL NUMBER;
    ERROR_NULOS EXCEPTION;
BEGIN
    FOR R_NUMERO_VENTA IN C_NUMERO_VENTA LOOP
        VAR_COMISION := R_NUMERO_VENTA.PRECIO_VENTA_FINAL*(P_PORCENTAJE_COMISION/100);
        VAR_VENTA_FINAL := R_NUMERO_VENTA.PRECIO_VENTA_FINAL + VAR_COMISION;
        
        IF VAR_COMISION IS NULL OR VAR_VENTA_FINAL IS NULL THEN
            RAISE ERROR_NULOS;
        ELSE
            UPDATE VENTA
            SET PORCENTAJE_COMISION = P_PORCENTAJE_COMISION, 
                COMISION = VAR_COMISION,
                VENTA_FINAL = VAR_VENTA_FINAL
            WHERE NUMERO_VENTA = R_NUMERO_VENTA.NUMERO_VENTA;
        END IF;
    END LOOP;
EXCEPTION
    WHEN ERROR_NULOS THEN
        DBMS_OUTPUT.PUT_LINE('Error valores o calculos nulos');
END MODIFICACION_PORCENTAJE_COMISION_Y_COMISION;



BEGIN
    MODIFICACION_PORCENTAJE_COMISION_Y_COMISION(15);
    COMMIT;
END;
/