CREATE VIEW VENTA_CLIENTE_COMPRADOR AS
	SELECT NUMERO_VENTA, FECHA_VENTA, VENTA_FINAL, NOMBRE_CLIENTE
	FROM VENTA V
	JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
	ORDER BY NUMERO_VENTA;


CREATE VIEW ARTISTA_OBRA_ARTE AS
	SELECT A.NOMBRE_ARTISTA, DIRECCION_ARTISTA, TITULO_OBRA, PRECIO_SOLICITADO
	FROM ARTISTAS A
	JOIN OBRAS_ARTE OA ON OA.NOMBRE_ARTISTA = A.NOMBRE_ARTISTA;


CREATE VIEW VENDEDOR_VENTA AS
	SELECT RUN_VENDEDOR, NOMBRE_VENDEDOR, FECHA_VENTA, COMISICION, VENTA_FINAL
	FROM VENDEDOR V
	JOIN VENTA VE ON VE.RUN_VENDEDOR = V.RUN_VENDEDOR;


CREATE VIEW ARTISTAS_ARTISTA_ENTREVISTA AS
	SELECT 
		A.NOMBRE_ARTISTA, 
		DIRECCION_ARTISTA, 
		TELEFONO_ARTISTA, 
		FECHA_ENTREVISTA, 
		NOMBRE_ENTREVISTADOR
	FROM ARTISTAS A
	JOIN ARTISTA_ENTREVISTA AE ON AE.NOMBRE_ARTISTA = A.NOMBRE_ARTISTA;





















