CREATE INDEX IDX_VENDEDOR_NOMBRE
ON VENDEDOR(NOMBRE_VENDEDOR);

CREATE INDEX IDX_VENDEDOR_DIRECCION
ON VENDEDOR(DIRECCION_VENDEDOR);

CREATE INDEX IDX_CLIENTE_COMPRADOR_NOMBRE
ON CLIENTE_COMPRADOR(NOMBRE_CLIENTE);

CREATE INDEX IDX_CLIENTE_COMPRADOR_CORREO
ON CLIENTE_COMPRADOR(CORREO_ELECTRONICO_CLIENTE);

CREATE INDEX IDX_EXPOSICIONES_NOMBRE
ON EXPOSICIONES(NOMBRE_ARTISTA_DESTACADO);

CREATE INDEX IDX_EXPOSICIONES_TEMA
ON EXPOSICIONES(TEMA_EXPOSICION);

CREATE INDEX IDX_ARTISTAS_TELEFONO
ON ARTISTAS(TELEFONO_ARTISTA);

CREATE INDEX IDX_ARTISTAS_DIRECCION
ON ARTISTAS(DIRECCION_ARTISTA);