ALTER TABLE ARTISTA_ENTREVISTA
DROP FOREIGN KEY ARTISTA_ENTREVISTA_ARTISTAS_FK;

ALTER TABLE ARTISTA_TOTALES_VENTAS
DROP FOREIGN KEY ARTISTA_TOTALES_VENTAS_ARTISTAS_FK;

ALTER TABLE ARTISTA_VENTAS
DROP FOREIGN KEY ARTISTA_VENTAS_ARTISTAS_FK;

ALTER TABLE CLIENTES_TOTALES
DROP FOREIGN KEY CLIENTES_TOTALES_CLIENTE_COMPRADOR_FK;

ALTER TABLE COLECCIONISTAS
DROP FOREIGN KEY COLECCIONISTAS_ARTISTAS_FK;

ALTER TABLE CONTACTA
DROP FOREIGN KEY CONTACTA_EXPOSICIONES_FK;

ALTER TABLE CONTACTA
DROP FOREIGN KEY CONTACTA_POTENCIALES_CLIENTES_FK;

ALTER TABLE EXPOSICIONES
DROP FOREIGN KEY EXPOSICIONES_ARTISTAS_FK;

ALTER TABLE OBRAS_ARTE
DROP FOREIGN KEY OBRAS_ARTE_ARTISTAS_FK;

ALTER TABLE OBRAS_ARTE
DROP FOREIGN KEY OBRAS_ARTE_COLECCIONISTAS_FK;

ALTER TABLE SE_EXHIBE
DROP FOREIGN KEY SE_EXHIBE_EXPOSICIONES_FK;

ALTER TABLE SE_EXHIBE
DROP FOREIGN KEY SE_EXHIBE_OBRAS_ARTE_FK;

ALTER TABLE SE_EXHIBE
DROP FOREIGN KEY SE_EXHIBE_VENTA_FK;

ALTER TABLE VENTA
DROP FOREIGN KEY VENTA_CLIENTE_COMPRADOR_FK;

ALTER TABLE VENTA
DROP FOREIGN KEY VENTA_COLECCIONISTAS_FK;

ALTER TABLE VENTA
DROP FOREIGN KEY VENTA_VENDEDOR_FK;


DROP TABLE ARTISTAS;
DROP TABLE ARTISTA_ENTREVISTA;
DROP TABLE ARTISTA_TOTALES_VENTAS;
DROP TABLE ARTISTA_VENTAS;
DROP TABLE CLIENTES_TOTALES;
DROP TABLE CLIENTE_COMPRADOR;
DROP TABLE COLECCIONISTAS;
DROP TABLE CONTACTA;
DROP TABLE EXPOSICIONES;
DROP TABLE OBRAS_ARTE;
DROP TABLE POTENCIALES_CLIENTES;
DROP TABLE SE_EXHIBE;
DROP TABLE VENDEDOR;
DROP TABLE VENTA;