-- FE DE ERRATAS
-- CAMPOS FECHA_ENTREVISTA y NOMBRE_ENTREVISTADOR SON CONDIDERADOS, PERO SE HACE LEFT JOIN A LA TABLA ARTISTA y LA CONDICION DE IS NULL EN EL WHERE PARA ASI OBTENER LOS ARTISTAS NO ENTREVISTADOS.
SELECT
	A.NOMBRE_ARTISTA,
    A.CONOCIDO,
    AE.FECHA_ENTREVISTA,
    AE.NOMBRE_ENTREVISTADOR
FROM ARTISTA_ENTREVISTA AE 
LEFT JOIN ARTISTAS A ON A.NOMBRE_ARTISTA = AE.NOMBRE_ARTISTA
LEFT JOIN OBRAS_ARTE OA ON OA.NOMBRE_ARTISTA = A.NOMBRE_ARTISTA
WHERE OA.NOMBRE_ARTISTA IS NULL AND A.NOMBRE_ARTISTA IS NULL