SELECT
	*
FROM
(
    SELECT 
        NOMBRE_ARTISTA,
        2019 'FECHA',
        TOTAL_VENTAS_ANIO_ANTERIOR TOTAL_VENTAS
    FROM ARTISTA_TOTALES_VENTAS

    UNION

    SELECT 
        NOMBRE_ARTISTA, 
        FECHA_ANIO_TOTALES_VENTAS FECHA,
        TOTAL_VENTAS_ANUAL TOTAL_VENTAS
    FROM ARTISTA_TOTALES_VENTAS
) AS A
ORDER BY A.NOMBRE_ARTISTA, A.FECHA, A.TOTAL_VENTAS