SELECT
	E.TITULO_EXPOSICION,
    E.FECHA_INICIO_EXPOSICION,
    E.FECHA_TERMINO_EXPOSICION,
    OA.NOMBRE_ARTISTA,
    OA.TITULO_OBRA,
    OA.ANIO_CREACION
FROM SE_EXHIBE SE
JOIN OBRAS_ARTE OA ON OA.NOMBRE_ARTISTA = SE.NOMBRE_ARTISTA AND OA.TITULO_OBRA = SE.TITULO_OBRA
JOIN EXPOSICIONES E ON E.TITULO_EXPOSICION = SE.TITULO_EXPOSICION
GROUP BY E.TITULO_EXPOSICION, E.FECHA_INICIO_EXPOSICION, E.FECHA_TERMINO_EXPOSICION, OA.NOMBRE_ARTISTA, OA.TITULO_OBRA, OA.ANIO_CREACION
HAVING MIN(OA.ANIO_CREACION) < 1935