SELECT
	A.NOMBRE_ARTISTA,
    A.TITULO_OBRA,
    A.PRECIO_VENTA_FINAL,
    A.PORCENTAJE_COMISION,
    A.VALOR_COMISION,
    A.PORCENTAJE_IVA,
    A.VALOR_IVA,
    A.VENTA_FINAL + A.VALOR_IVA 'VENTA FINAL + IVA' 
FROM
(
    SELECT
        OA.NOMBRE_ARTISTA, 
        OA.TITULO_OBRA,
        V.PRECIO_VENTA_FINAL,
        V.PORCENTAJE_COMISION,
        V.COMISION 'VALOR_COMISION',
    	19 'PORCENTAJE_IVA',
        V.PRECIO_VENTA_FINAL * 0.19 'VALOR_IVA',
        V.VENTA_FINAL
    FROM SE_EXHIBE SE
    JOIN OBRAS_ARTE OA ON OA.NOMBRE_ARTISTA = SE.NOMBRE_ARTISTA AND OA.TITULO_OBRA = SE.TITULO_OBRA
    JOIN VENTA V ON V.NUMERO_VENTA = SE.NUMERO_VENTA
)AS A