CREATE TABLE ESTUDIANTE
(
	ID_ESTUDIANTE INTEGER NOT NULL,
	NOMBRE_ESTUDIANTE VARCHAR(200),
	APELLIDO_ESTUDIANTE VARCHAR(200),
	RUN VARCHAR(200)
);
ALTER TABLE ESTUDIANTE ADD CONSTRAINT ESTUDIANTE_PK 
	PRIMARY KEY (ID_ESTUDIANTE);

CREATE TABLE CURSO
(
	ID_CURSO INTEGER NOT NULL,
	NOMBRE_CURSO VARCHAR(200),
	CODIGO_CURSO VARCHAR(200),
	ID_DOCENTE INTEGER
);
ALTER TABLE CURSO ADD CONSTRAINT CURSO_PK 
	PRIMARY KEY (ID_CURSO);

CREATE TABLE MATRICULADO
(
	ID_MATRICULADO INTEGER NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	ID_ESTUDIANTE INTEGER NOT NULL
);
ALTER TABLE MATRICULADO ADD CONSTRAINT MATRICULADO_PK
	PRIMARY KEY (ID_MATRICULADO);

-- Creacion claves foraneas
ALTER TABLE MATRICULADO 
ADD CONSTRAINT MATRICULADO_CURSO_FK
FOREIGN KEY (ID_CURSO)
REFERENCES CURSO (ID_CURSO)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE MATRICULADO
ADD CONSTRAINT MATRICULADO_ESTUDIANTE_FK
FOREIGN KEY (ID_ESTUDIANTE)
REFERENCES ESTUDIANTE (ID_ESTUDIANTE)
ON DELETE CASCADE
ON UPDATE CASCADE;

-- Insertar datos.
INSERT INTO ESTUDIANTE(ID_ESTUDIANTE, NOMBRE_ESTUDIANTE, APELLIDO_ESTUDIANTE, RUN)
VALUES(1,'SACARIAS','FLORES DEL CAMPO','00.000.000-0');
INSERT INTO ESTUDIANTE(ID_ESTUDIANTE, NOMBRE_ESTUDIANTE, APELLIDO_ESTUDIANTE, RUN)
VALUES(2,'ARMANDO','CASAS DEL BOSQUE','11.111.111-1');

INSERT INTO CURSO(ID_CURSO, NOMBRE_CURSO, CODIGO_CURSO, ID_DOCENTE)
VALUES(1,'BASE DE DATOS II','BD2',1);
INSERT INTO CURSO(ID_CURSO, NOMBRE_CURSO, CODIGO_CURSO, ID_DOCENTE)
VALUES(2,'TALLER DE SISTEMAS I','TSI',1);

INSERT INTO MATRICULADO(ID_MATRICULADO, ID_CURSO, ID_ESTUDIANTE)
VALUES(1,1,1);
INSERT INTO MATRICULADO(ID_MATRICULADO, ID_CURSO, ID_ESTUDIANTE)
VALUES(2,1,2);
INSERT INTO MATRICULADO(ID_MATRICULADO, ID_CURSO, ID_ESTUDIANTE)
VALUES(3,2,1);
INSERT INTO MATRICULADO(ID_MATRICULADO, ID_CURSO, ID_ESTUDIANTE)
VALUES(4,2,2);




















