--Cuando queremos consultar columnas o atributos de dos o mas tablas se debe utilizar JOIN

SELECT M.ID_MATRICULADO, E.NOMBRES, E.APELLIDOS, C.NOMBRE_CURSO
FROM MATRICULADO M 
JOIN ESTUDIANTE E ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
JOIN CURSO C ON M.ID_CURSO = C.ID_CURSO;

SELECT M.ID_MATRICULADO, E.NOMBRES, E.APELLIDOS, C.NOMBRE_CURSO
FROM MATRICULADO M 
LEFT JOIN ESTUDIANTE E ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
LEFT JOIN CURSO C ON M.ID_CURSO = C.ID_CURSO;

SELECT M.ID_MATRICULADO, E.NOMBRES, E.APELLIDOS, C.NOMBRE_CURSO
FROM MATRICULADO M 
RIGHT JOIN ESTUDIANTE E ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
RIGHT JOIN CURSO C ON M.ID_CURSO = C.ID_CURSO;

SELECT M.ID_MATRICULADO, E.NOMBRES, E.APELLIDOS, C.NOMBRE_CURSO
FROM MATRICULADO M 
INNER JOIN ESTUDIANTE E ON M.ID_ESTUDIANTE = E.ID_ESTUDIANTE
INNER JOIN CURSO C ON M.ID_CURSO = C.ID_CURSO;