-- Borrado de Claves Foraneas
ALTER TABLE MATRICULADO
DROP FOREIGN KEY MATRICULADO_CURSO_FK;

ALTER TABLE MATRICULADO
DROP FOREIGN KEY MATRICULADO_ESTUDIANTE_FK;

-- Borrado de tablas
BEGIN TRANSACTION
DROP TABLE MATRICULADO;
DROP TABLE ESTUDIANTE;
DROP TABLE CURSO;
COMMIT;