-- CANTIDAD DE CURSOS QUE TIENE CADA ESTUDIANTE.
SELECT
  E.NOMBRE_ESTUDIANTE,
  E.APELLIDO_ESTUDIANTE,
  COUNT(M.ID_CURSO) CANT_CURSO
FROM MATRICULADO M
JOIN ESTUDIANTE E ON E.ID_ESTUDIANTE = M.ID_ESTUDIANTE
GROUP BY E.NOMBRE_ESTUDIANTE, E.APELLIDO_ESTUDIANTE;

-- CANTIDAD DE ESTUDIANTES QUE TIENE CADA CURSO.
SELECT
  C.NOMBRE_CURSO,
  C.CODIGO_CURSO,
  COUNT(M.ID_ESTUDIANTE) CANT_ESTUDIANTES
FROM MATRICULADO M
JOIN CURSO C ON C.ID_CURSO = M.ID_CURSO
GROUP BY C.NOMBRE_CURSO, C.CODIGO_CURSO;