SELECT
    COUNT(V.NUMERO_VENTA) COUNT_NUMERO_VENTA,
    CC.NOMBRE_CLIENTE,
    CC.RECIBO,
    CT.TOTAL_COMPRAS_A_LA_FECHA
FROM VENTA V
JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
JOIN CLIENTES_TOTALES CT ON CT.RUN_CLIENTE = CC.RUN_CLIENTE
GROUP BY CC.NOMBRE_CLIENTE, CC.RECIBO, CT.TOTAL_COMPRAS_A_LA_FECHA
HAVING COUNT(V.NUMERO_VENTA) >= 2;