UPDATE EXPOSICIONES
SET TITULO_EXPOSICION = 'Lo mejor de Pablo Picasso'
WHERE TITULO_EXPOSICION = 'Lo mejor del arte III';

ALTER TABLE CONTACTA
DROP FOREIGN KEY CONTACTA_POTENCIALES_CLIENTES_FK;

ALTER TABLE CONTACTA
DROP FOREIGN KEY CONTACTA_EXPOSICIONES_FK;

DROP TABLE POTENCIALES_CLIENTES;