SELECT
    V.RUN_VENDEDOR,
    V.FECHA_VENTA,
    V.VENTA_FINAL,
    VE.NOMBRE_VENDEDOR,
    CC.NOMBRE_CLIENTE,
    CT.TOTAL_COMPRAS_A_LA_FECHA
FROM `VENTA` V
JOIN VENDEDOR VE ON V.RUN_VENDEDOR = VE.RUN_VENDEDOR
JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
JOIN CLIENTES_TOTALES CT ON CT.RUN_CLIENTE = CC.RUN_CLIENTE
WHERE V.FECHA_VENTA BETWEEN '2020-04-20 00:00:00' AND '2020-04-20 23:59:59'