SELECT 
	A.NOMBRE_ARTISTA, 
	A.CONOCIDO, 
	ATV.TOTAL_VENTAS_ANUAL, 
	ATV.TOTAL_VENTAS_ANIO_ANTERIOR
FROM ARTISTAS A
JOIN ARTISTA_TOTALES_VENTAS ATV ON ATV.NOMBRE_ARTISTA = A.NOMBRE_ARTISTA
WHERE A.NOMBRE_ARTISTA = ALL 
(
	SELECT E.NOMBRE_ARTISTA 
	FROM EXPOSICIONES E 
	WHERE E.FECHA_INICIO_EXPOSICION BETWEEN '19-04-2018' AND '19-04-2020' 
	GROUP BY E.NOMBRE_ARTISTA
);