SELECT 
	OA.NOMBRE_ARTISTA, 
	OA.TITULO_OBRA, 
	OA.ANIO_CREACION, 
	SE.TITULO_EXPOSICION
FROM OBRAS_ARTE OA
LEFT JOIN SE_EXHIBE SE ON SE.NOMBRE_ARTISTA = OA.NOMBRE_ARTISTA AND SE.TITULO_OBRA = OA.TITULO_OBRA
WHERE NOT EXISTS 
(
	SELECT V.NUMERO_VENTA 
	FROM `VENTA` V
	WHERE V.FECHA_VENTA BETWEEN '2020-01-01' AND '2020-12-31'
	GROUP BY V.NUMERO_VENTA
);