SELECT
    A.NOMBRE_ARTISTA,
    E.TITULO_EXPOSICION,
    E.TEMA_EXPOSICION
FROM `ARTISTAS` A
JOIN EXPOSICIONES E ON E.NOMBRE_ARTISTA = A.NOMBRE_ARTISTA
WHERE A.NOMBRE_ARTISTA IN ('PABLO PICASSO','LEONARDO DA VINCI');