SELECT
    NOMBRE_ARTISTA,
    TOTAL_VENTAS_ANUAL,
    TOTAL_VENTAS_ANIO_ANTERIOR,
    CASE 
        WHEN TOTAL_VENTAS_ANUAL > TOTAL_VENTAS_ANIO_ANTERIOR THEN 'VENTAS ALTAS'
        WHEN TOTAL_VENTAS_ANUAL < TOTAL_VENTAS_ANIO_ANTERIOR THEN 'VENTAS BAJAS'
        ELSE 'VENTAS IGUALES' 
    END AS 'COMPARACION VENTAS'
FROM `ARTISTA_TOTALES_VENTAS`
ORDER BY NOMBRE_ARTISTA;