SELECT
	A.NOMBRE_COLECCIONISTA,
    MAX(A.CANT_TITULO_OBRA) MAX_CANT_TITULO_OBRA,
    A.NOMBRE_ARTISTA
FROM
(
    SELECT
        C.NOMBRE_COLECCIONISTA,
        COUNT(OA.TITULO_OBRA) CANT_TITULO_OBRA,
        OA.NOMBRE_ARTISTA
    FROM OBRAS_ARTE OA
    JOIN COLECCIONISTAS C ON C.NOMBRE_COLECCIONISTA = OA.NOMBRE_COLECCIONISTA
    GROUP BY C.NOMBRE_COLECCIONISTA, OA.NOMBRE_ARTISTA
) AS A
GROUP BY A.NOMBRE_COLECCIONISTA, A.NOMBRE_ARTISTA