SELECT
	V.RUN_CLIENTE,
    CC.NOMBRE_CLIENTE,
    COUNT(VE.RUN_VENDEDOR) CANT_RUN_VENDEDOR,
    VE.RUN_VENDEDOR,
    VE.NOMBRE_VENDEDOR
FROM VENTA V
JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
JOIN VENDEDOR VE ON VE.RUN_VENDEDOR = V.RUN_VENDEDOR
GROUP BY V.RUN_CLIENTE, CC.NOMBRE_CLIENTE, VE.RUN_VENDEDOR, VE.NOMBRE_VENDEDOR