SELECT
	*
FROM
(
    SELECT
        COUNT(PC.NOMBRE_POTENCIALES_CLIENTES) CANT_NOMBRE_POTENCIALES_CLIENTES,
        E.TITULO_EXPOSICION
    FROM CONTACTA C
    JOIN POTENCIALES_CLIENTES PC ON PC.NOMBRE_POTENCIALES_CLIENTES = C.NOMBRE_POTENCIALES_CLIENTES
    JOIN EXPOSICIONES E ON E.TITULO_EXPOSICION = C.TITULO_EXPOSICION
    GROUP BY E.TITULO_EXPOSICION
)AS A
ORDER BY A.CANT_NOMBRE_POTENCIALES_CLIENTES;