SELECT
	*
FROM
(
    SELECT
        E.TITULO_EXPOSICION,
        E.NOMBRE_ARTISTA_DESTACADO,
        SE.TITULO_OBRA,
        SUM(V.VENTA_FINAL) SUM_VENTA_FINAL,
        CC.RUN_CLIENTE,
        CC.NOMBRE_CLIENTE
    FROM SE_EXHIBE SE
    JOIN EXPOSICIONES E ON E.TITULO_EXPOSICION = SE.TITULO_EXPOSICION
    JOIN VENTA V ON V.NUMERO_VENTA = SE.NUMERO_VENTA
    JOIN CLIENTE_COMPRADOR CC ON CC.RUN_CLIENTE = V.RUN_CLIENTE
    GROUP BY E.TITULO_EXPOSICION, E.NOMBRE_ARTISTA_DESTACADO, SE.TITULO_OBRA, CC.RUN_CLIENTE, CC.NOMBRE_CLIENTE
)AS A 
ORDER BY A.SUM_VENTA_FINAL DESC