DECLARE
  SUMA INTEGER := 0;
  INCREMENTO INTEGER;
BEGIN
  FOR INCREMENTO IN 1..10 LOOP
    SUMA := SUMA + INCREMENTO;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Resultado suma es: ' || TO_CHAR(SUMA));
END;
/