DECLARE
  RESULTADO INTEGER := 1;
  INCREMENTO INTEGER := 1;
BEGIN
  LOOP 
    RESULTADO := RESULTADO * INCREMENTO;
    INCREMENTO := INCREMENTO + 1;
    EXIT WHEN (INCREMENTO > 10);
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Resultado multiplicacion es: ' || TO_CHAR(RESULTADO));
END;
/