DECLARE
  NUMERO_A INTEGER := 2;
  NUMERO_B INTEGER := 3;
  RESULTADO INTEGER := 0;
  ERROR_SUMA_CERO EXCEPTION;
BEGIN
  
  RESULTADO := NUMERO_A + NUMERO_B;
  
  IF RESULTADO = 0 THEN
    RAISE ERROR_SUMA_CERO;
  ELSE
    DBMS_OUTPUT.PUT_LINE('Resultado suma es: ' || TO_CHAR(RESULTADO));
  END IF;
  
EXCEPTION
  WHEN ERROR_SUMA_CERO THEN
    DBMS_OUTPUT.PUT_LINE('Error suma es cero, modificar numeros.');
END;
/