DECLARE
  RESULTADO INTEGER := 1;
  INCREMENTO INTEGER;
BEGIN
  FOR INCREMENTO IN 1..10 LOOP
    RESULTADO := RESULTADO * INCREMENTO;
  END LOOP;
  DBMS_OUTPUT.PUT_LINE('Resultado multiplicacion es: ' || TO_CHAR(RESULTADO));
END;
/